#! /usr/bin/env python

import os
import string
import sys

from random import choice

import click

allowed_symbols = '!#*+,-/?@^_~'

@click.command()
@click.option('--num_chars', help='How many chars.', type=int, required=True)
def run(num_chars):
    allowed_chars = string.ascii_letters + allowed_symbols + string.digits
    password = "".join(choice(allowed_chars) for x in range(num_chars))
    print(password)

if __name__ == "__main__":
    run()
