#!/bin/bash
set -x  # echo all commands run on this script, expanding its variables

source host-postgres.env
source ../../notepy.env

NEWUSERPASSWORD=$PGPASSWORD
PGPASSWORD="$HOST_PGPASSWORD" psql -h $POSTGRES_HOST -p $POSTGRES_PORT -U $HOST_POSTGRES_USER -c "CREATE USER $POSTGRES_USER WITH PASSWORD '$NEWUSERPASSWORD';"
PGPASSWORD="$HOST_PGPASSWORD" psql -h $POSTGRES_HOST -p $POSTGRES_PORT -U $HOST_POSTGRES_USER -c "CREATE DATABASE $POSTGRES_DB WITH OWNER = '$POSTGRES_USER';"
PGPASSWORD="$HOST_PGPASSWORD" psql -h $POSTGRES_HOST -p $POSTGRES_PORT -U $HOST_POSTGRES_USER -c "ALTER ROLE $POSTGRES_USER SET client_encoding TO 'utf8';"
PGPASSWORD="$HOST_PGPASSWORD" psql -h $POSTGRES_HOST -p $POSTGRES_PORT -U $HOST_POSTGRES_USER -c "ALTER ROLE $POSTGRES_USER SET default_transaction_isolation TO 'read committed';"
PGPASSWORD="$HOST_PGPASSWORD" psql -h $POSTGRES_HOST -p $POSTGRES_PORT -U $HOST_POSTGRES_USER -c "ALTER ROLE $POSTGRES_USER SET timezone TO 'UTC';"
PGPASSWORD="$HOST_PGPASSWORD" psql -h $POSTGRES_HOST -p $POSTGRES_PORT -U $HOST_POSTGRES_USER -c "GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;"

PGPASSWORD="$HOST_PGPASSWORD" psql -h $POSTGRES_HOST -U postgres -p $POSTGRES_PORT -c "\l";
