# Generated by Django 2.0.4 on 2018-05-09 01:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('0ad5f990-de00-4bcb-a573-ceac53b43ffa'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notetag',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1558685a-018b-425d-b16f-51858b0b1f21'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('dee36a2e-20a7-440a-9dfa-d7e4b1fad994'), editable=False, primary_key=True, serialize=False),
        ),
    ]
