# Generated by Django 2.0.4 on 2018-05-09 00:50

from django.db import migrations, models
import markdownx.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='private',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5d446301-c251-499f-9386-35d7c7fffccd'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notetag',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('0e18ad1e-f51b-43ef-8e46-b3907f8d2ede'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('dba40ab9-6b64-4dd3-8194-537418db6983'), editable=False, primary_key=True, serialize=False),
        ),
    ]
