# Generated by Django 2.0.4 on 2018-04-22 22:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='uri',
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('owner', 'name')},
        ),
        migrations.AlterIndexTogether(
            name='note',
            index_together={('owner', 'created')},
        ),
    ]
