# Generated by Django 2.0.5 on 2018-08-06 11:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('04c51bce-01e9-408f-9b15-b7099d0ee872'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notetag',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d4fefb68-f6a0-4408-8575-1627536801db'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('17f568f1-37b1-4d2b-9614-5ce056668cc6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
