# Generated by Django 2.0.5 on 2018-08-06 12:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20180806_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notetag',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4f9a10ba-ac07-42b0-840e-2ecc556aada4'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d0457a83-a78c-4e5f-92b6-8550239b5b45'), editable=False, primary_key=True, serialize=False),
        ),
    ]
